@baseUrl = http://localhost:3333

# @name upload-banner
POST {{baseUrl}}/banners
Content-Type: multipart/form-data; boundary=WebKitFormBoundary7MA4YWxkTrZu0gW

--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="banner.jpg"
Content-Type: image/jpeg

< ./test/fixtures/banner.jpg
-WebKitFormBoundary7MA4YWxkTrZu0gW--

