@baseUrl = http://localhost:3333

# @name register
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "John Doe",
    "username": "johndoe",
    "email": "johndoe@alu.ufc.br",
    "password": "123456",
    "semester": 3
}

###

# @name login
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "johndoe@alu.ufc.br",
    "password": "123456"
}
